behaviors:
  ShadowAgent7Alt:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.1
        gamma: 0.99
        encoding_size: 128
        learning_rate: 5.0e-4
    max_steps: 500000
    time_horizon: 64
    summary_freq: 2500
    keep_checkpoints: 20
    checkpoint_interval: 25000
environment_parameters:
  object:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0
      max_value: 2.99
