behaviors:
  ShadowAgent8:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.2
        gamma: 0.99
        encoding_size: 128
        learning_rate: 3.0e-4
    max_steps: 500000
    time_horizon: 64
    summary_freq: 2500
    keep_checkpoints: 20
    checkpoint_interval: 25000
environment_parameters:
  object:
    curriculum:
      - name: Teapot # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: ShadowAgent8
          signal_smoothing: true
          min_lesson_length: 25
          threshold: 0.2
        value: 0
      - name: Crocodile # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: ShadowAgent8
          signal_smoothing: true
          min_lesson_length: 25
          threshold: 0.6
          require_reset: true
        value: 1
      - name: Elephant
        value: 2
